### ISSUE TITLE
WPF support for applets

### ISSUE THREAD

**Issue by sidewinder94** [sidewinder94/Logitech-LCD#2]
Add WPF support for applets

**Comment by FyZiK** [comment]
How do i show a picture in my applet? Can you please give me a Step by Step Instruction?

**Comment by sidewinder94** [comment]
This should go in a new issue....
This has nothing to do wit  WPF...
But basically, you'll need to init the keyboard with : 
```
LogitechLcd.Instance.Init("GWvW Timers", LcdType.Color | LcdType.Mono)
```
Then you can display the image with 
```
LogitechLcd.Instance.ColorSetBackground()
```

And too see how to convert a Bitmap Object into a byte array, i'll ask you to go and check this method : https://github.com/sidewinder94/Logitech-LCD/blob/master/Logitech-LCD/Applets/BaseApplet.cs#L185
