### ISSUE TITLE
How to send WinForm UserControl to LCD?

### ISSUE THREAD

**Issue by roxaskeyheart** [sidewinder94/Logitech-LCD#5]
Hi there,
Awesome work on this wrapper library, it's proven very useful.

I was wondering if you might be able to point me in the right direction for using WinForm UserControls with your library? I followed you instructions to create a new control which inherits off the Logitech_LCD.Applets.BaseApplet class and then implemented an override to the OnDataUpdate() event, however I'm not actually sure what to do next.

I basically want to achieve having multiple user controls or "pages" to send to the LCD, I can create a new instance of the user control using standard syntax such as:

var page = new MyUserControl();

but then how do i send that to update on the LCD, or more accurately - set that UserControl active to the screen?

Any help would be much appreciated.

**Comment by sidewinder94** [comment]
Hi,

Thanks for the feedback, feels nice !

On to your problem now.

If I understood correctly, you'd want to change the active applet during runtime.

Well, the Logitech SDK is really "simple", you just send it an image, and you can query it for which buttons are pressed.

I'll update the code to add a boolean to the base applet to allow you to ask an applet to stop sending it's updates to the screen, you'll still need to manage them to set which one will send it's updates to the screen.

Hope it made some sense.

I'll probably add an applet manager of sorts in the future to allow multiple usercontrols instantiated at the same time and the update management would be done by it.

**Comment by roxaskeyheart** [comment]
I ended up downloading your source code and changing a heap of stuff to make it cross-thread safe.. it was causing a few headaches since my app using multiple tasks to run stuff (including LCD stuff) in the background.

I managed to get it working by changing your Timers to System.Timers.Timer and I also split the BaseApplet class to two separate classes so I can send different content to Monochrome and Colour screens at the same time.

It's kinda working? Since you have LCD updates built into the UserControl, i have a variable which holds which active "page" (control) I want to send and then based on the buttons pushed it cycles through them by disposing the old page and feeding in the new page - that is kinda causing a lot of issues though, since when I try and dispose, I get a race error from the timer. Gotta love timers and threading in C# o.o;

**Comment by sidewinder94** [comment]
Hum, were you constrained by anything ? For this kind of stuff, I would have gone with the WPF applet...

Way easier to cycle different pages/UserControls (just replace the `Content` property of the applet Usercontrol).

Check out the above commit and see if it would help. You'd just have to be sure to only have one "Active" applet at the same time.

**Comment by roxaskeyheart** [comment]
Indeed, unfortunately the rest of the app is currently in WinForms and it's going to be a real pain to port it over to WPF. :(

I think the logic I'm using is just really bad, lol. It goes something like this:

    private static BaseAppletM _selectedMonoControl;
    private static int _page = 1;
    private static int _lastpage = 2;
    private const int MaxPage = 3;
    
    private void SwitchPages(int page)
        {
            if (_page == _lastpage) return;
            
            Logitech_LCD.LogitechLcd.Instance.MonoSetText(0, @"");
            Logitech_LCD.LogitechLcd.Instance.MonoSetText(1, @"");
            Logitech_LCD.LogitechLcd.Instance.MonoSetText(2, @"");
            Logitech_LCD.LogitechLcd.Instance.MonoSetText(3, @"");
            
            if (_selectedMonoControl != null)
            {
                _selectedMonoControl.LcdMonoButton0Pressed -= SelectedMonoControlOnLcdMonoButton0Pressed;
                _selectedMonoControl.LcdMonoButton3Pressed -= SelectedMonoControlOnLcdMonoButton3Pressed;
                _selectedMonoControl.Dispose();
                _selectedMonoControl = null;
            }
            
            switch (page)
            {
                case 1:
                    //Eorzea Time
                    _selectedMonoControl = new LCD_MONO_EorzeaTime();
                   
                    _lastpage = page;
                    break;
                case 2:
                    //Server Time
                    _selectedMonoControl = new LCD_MONO_ServerTime();

                    _lastpage = page;
                    break;
                case 3:
                    //Local Time
                    _selectedMonoControl = new LCD_MONO_LocalTime();

                    _lastpage = page;
                    break;
            }
            
            
            if (_selectedMonoControl != null)
            {
                _selectedMonoControl.LcdMonoButton0Pressed += SelectedMonoControlOnLcdMonoButton0Pressed;
                _selectedMonoControl.LcdMonoButton3Pressed += SelectedMonoControlOnLcdMonoButton3Pressed;
            }
            
        }

        private void SelectedMonoControlOnLcdMonoButton3Pressed(object sender, EventArgs eventArgs)
        {
            _page++;
            if (_page > MaxPage) _page = 1;
            Console.WriteLine(@"Button Pressed 3 " + _page + @"/" + _lastpage);
            SwitchPages(_page);
        }

        private void SelectedMonoControlOnLcdMonoButton0Pressed(object o, EventArgs eventArgs)
        {
            _page--;
            if (_page <= 0) _page = MaxPage;
            Console.WriteLine(@"Button Pressed 0 " + _page + @"/" + _lastpage);
            SwitchPages(_page);
        }

**Comment by sidewinder94** [comment]
Eorzea ftw \o/

Not wanting to force you to do anything, but there is a WPF component called `WindowsFormHost` which would allow displaying WinForms content in a WPF UserControl.

That and nothing prevents you from having both WinForms and WPF in your app :p

I may be at fault here for the timer exception after disposing.

Never encountered the use case.

Let me check out how to do it properly and I'll have a nice override of the Dispose method ready.

I'll be keeping you up to date.

**Comment by roxaskeyheart** [comment]
I'll certainly have to look into that for the future then.

It's probably worth noting I couldn't get your timers to work when i first downloaded your code, they just would not start. I think it again had something to do with trying to call them from a different thread. That was why i needed to change them to System.Timers.Timer.

Here is what I ended up doing to your BaseApplet if you were interested:

```
using Logitech_LCD.Exceptions;
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Timers;
using System.Windows;
using System.Windows.Forms;
using Logitech_LCD.Utils;

namespace Logitech_LCD.Applets
{
    public class BaseAppletM : UserControl
    {
        private readonly int _height;
        private readonly int _width;
        private readonly LcdType? _lcdType;

        public event EventHandler DataUpdate;

        //Color LCD button events
        public event EventHandler LcdColorLeftButtonPressed;
        public event EventHandler LcdColorRightButtonPressed;
        public event EventHandler LcdColorUpButtonPressed;
        public event EventHandler LcdColorDownButtonPressed;
        public event EventHandler LcdColorOkButtonPressed;
        public event EventHandler LcdColorCancelButtonPressed;
        public event EventHandler LcdColorMenuButtonPressed;

        //Mono LCD Button Events
        public event EventHandler LcdMonoButton0Pressed;
        public event EventHandler LcdMonoButton1Pressed;
        public event EventHandler LcdMonoButton2Pressed;
        public event EventHandler LcdMonoButton3Pressed;

        //Timers
        private System.Timers.Timer _updateTimer;
        private Task buttonCheckTimer;
        private CancellationTokenSource _buttonCheckTimer;

        private static bool dispose;


        public BaseAppletM()
            : this(StaticMethods.DetectLcdType())
        {

        }

        public BaseAppletM(LcdType? lcdType)
        {
            if (lcdType != null)
            {
                _lcdType = lcdType;
                
                _buttonCheckTimer = new CancellationTokenSource();

                //, TaskCreationOptions.LongRunning

                buttonCheckTimer = new Task(async () =>
                {
                    await CallCheckButtons(_buttonCheckTimer.Token);
                });

                
                _updateTimer = new System.Timers.Timer
                {
                    Interval = 100,
                    AutoReset = true
                };
                _updateTimer.Elapsed += UpdateGraphics;
                
                _height = (int)MonoBitmap.Height;
                _width = (int)MonoBitmap.Width;

                DataUpdate += OnDataUpdate;
                
                buttonCheckTimer.Start();
                _updateTimer.Start();
            }
        }

        private async Task CallCheckButtons(CancellationToken ct)
        {
            while (!ct.IsCancellationRequested)
            {
                await Task.Delay(50, ct).ConfigureAwait(false);
                CheckButtons();
            }
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dispose = true;

                OnDisposal(this, EventArgs.Empty);
                DataUpdate -= OnDataUpdate;

                _buttonCheckTimer.Cancel();
                _updateTimer.Stop();

                _updateTimer.Dispose();
                _buttonCheckTimer.Dispose();
            }

            base.Dispose(disposing);
        }

        private void CheckButtons()
        {
            if (dispose) return;

            if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorLeft))
            {
                if (LcdColorLeftButtonPressed != null)
                {
                    LcdColorLeftButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorRight))
            {
                if (LcdColorRightButtonPressed != null)
                {
                    LcdColorRightButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorUp))
            {
                if (LcdColorUpButtonPressed != null)
                {
                    LcdColorUpButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorDown))
            {
                if (LcdColorDownButtonPressed != null)
                {
                    LcdColorDownButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorOk))
            {
                if (LcdColorOkButtonPressed != null)
                {
                    LcdColorOkButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorCancel))
            {
                if (LcdColorCancelButtonPressed != null)
                {
                    LcdColorCancelButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.ColorMenu))
            {
                if (LcdColorMenuButtonPressed != null)
                {
                    LcdColorMenuButtonPressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.MonoButton0))
            {
                if (LcdMonoButton0Pressed != null)
                {
                    LcdMonoButton0Pressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.MonoButton1))
            {
                if (LcdMonoButton1Pressed != null)
                {
                    LcdMonoButton1Pressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.MonoButton2))
            {
                if (LcdMonoButton2Pressed != null)
                {
                    LcdMonoButton2Pressed(this, EventArgs.Empty);
                }
            }
            else if (LogitechLcd.Instance.IsButtonPressed(Buttons.MonoButton3))
            {
                if (LcdMonoButton3Pressed != null)
                {
                    LcdMonoButton3Pressed(this, EventArgs.Empty);
                }
            }
        }
        
        private void UpdateGraphics(object sender, ElapsedEventArgs e)
        {
            if (dispose) return;

            try
            {
                DataUpdate?.Invoke(this, EventArgs.Empty);
                PixelFormat format = PixelFormat.Format32bppArgb;
                
                Bitmap bm = new Bitmap(_width, _height, format);

                if (InvokeRequired)
                {
                    Invoke((Action)delegate { DrawToBitmap(bm, new Rectangle(0, 0, _width, _height)); });
                }
                else
                {
                    DrawToBitmap(bm, new Rectangle(0, 0, _width, _height));
                }

                byte[] pixels = new byte[_width * _height * 4];

                BitmapData bitmapData = bm.LockBits(
                    new Rectangle(0, 0, _width, _height),
                    ImageLockMode.ReadOnly,
                    format);

                Marshal.Copy(bitmapData.Scan0, pixels, 0, pixels.Length);

                bm.UnlockBits(bitmapData);

                LogitechLcd.Instance.MonoSetBackground(StaticMethods.ConvertToMonochrome(pixels));
                
                LogitechLcd.Instance.Update();
            }
            catch (Exception exception)
            {
                //Console.WriteLine(exception);
            }
        }


        protected virtual void OnDataUpdate(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }

        protected virtual void OnDisposal(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by sidewinder94** [comment]
Well, you've already done the work of overriding the Dispose method !

May I ask the need for the OnDisposal method/event ? For the cancellation Token ? 

The timers not starting is weird, I'll change them to `System.timers.Timer` if it seems to work for you.

**Comment by roxaskeyheart** [comment]
Well this code is still giving me some trouble, so I'm still trying to work out why.

The OnDisposal method is there so I can override it from my own UserControl (which inherits), exactly the same way as OnDataUpdate does. This allows me to dispose elements of my UserControl when the parent one disposes - as that was causing some issues for me earlier.

Still working out the bugs though.. :/

**Comment by sidewinder94** [comment]
Ok, wait a little for me, I'm setting up a protected Dispose method, you won't need the OnDispose one.

You'll just need a `base()` call when overriding it !

**Comment by roxaskeyheart** [comment]
No worries. Thanks for helping me with this.. ^_^;

Currently the biggest problem I'm seeing revolves around this part:

```
private void UpdateGraphics(object sender, ElapsedEventArgs e)
        {
            if (dispose) return;

            try
            {
                DataUpdate?.Invoke(this, EventArgs.Empty);
                PixelFormat format = PixelFormat.Format32bppArgb;
                
                Bitmap bm = new Bitmap(_width, _height, format);

                if (InvokeRequired)
                {
                    Invoke((Action)delegate { DrawToBitmap(bm, new Rectangle(0, 0, _width, _height)); });
                }
                else
                {
                    DrawToBitmap(bm, new Rectangle(0, 0, _width, _height));
                }

                byte[] pixels = new byte[_width * _height * 4];

                BitmapData bitmapData = bm.LockBits(
                    new Rectangle(0, 0, _width, _height),
                    ImageLockMode.ReadOnly,
                    format);

                Marshal.Copy(bitmapData.Scan0, pixels, 0, pixels.Length);

                bm.UnlockBits(bitmapData);

                LogitechLcd.Instance.MonoSetBackground(StaticMethods.ConvertToMonochrome(pixels));
                
                LogitechLcd.Instance.Update();
            }
            catch (Exception exception)
            {
                //Console.WriteLine(exception);
            }
        }
```
When I attempt to dispose this Applet, it conflicts with the Timer which is running that method and since that method also contains multiple invokes, it is like a trio of what seems to be know as "race conditions" (?) which deadlocks the timer and then throws exceptions cause that method is trying to run still while everything else (ie. the controls) are now disposed.
.

**Comment by sidewinder94** [comment]
Try with these last modifications.

I took care of Stopping and disposing the timers in the Dispose method for both applets. Might correct some of your issues.

In any cases, with the new `IsActive` property on both applet , you should not need to dispose of them anymore. Effectively working around these issues.

**Comment by roxaskeyheart** [comment]
It's definitely a lot neater now, thanks ^^;

Still having some trouble with the OnDataUpdate() method though as it keeps trying to access disposed objects even though I have an IsActive check at the beginning.

```
protected override void OnDataUpdate(object sender, EventArgs e)
        {
            if (!IsActive) return;

            try
            {
                var _et = FFXIVHelpers.FetchEorzeaTime();
                var eorzeatime = _et.ToString("hh:mm tt");

                if (InvokeRequired)
                {
                    lbl_et_test.Invoke((Action) delegate { lbl_et_test.Text = eorzeatime; });
                }
                else
                {
                    lbl_et_test.Text = eorzeatime;
                }
            }
            catch (Exception exception)
            {
                //
            }
        }
```
Hmm

**Comment by sidewinder94** [comment]
The check won't help if the objects are disposed..... let's say between the if and the try.

Sorry, but I can't help you much more than that if it's in your app code, not that I don't want to, but I miss a lot of the context and don't have much more time on my hands ^^'

Try and see which object throws the exception, and if you can try to test if it's still available when you make the call.

That or wrapping it up in a catch block.... Not the most elegant solution, but you'd be able to dismiss the particular raised exception.

**Comment by roxaskeyheart** [comment]
It's all good, i ended up being about to resolve it by commenting out 

    base.Dispose(disposing);

in the BaseApplet and then using try catch blocks to dodge the exceptions.

Thanks for all your help though, I really do appreciate it. :)
