### ISSUE TITLE
How can I show the LCD Message

### ISSUE THREAD

**Issue by sbblg** [sidewinder94/Logitech-LCD#6]
My mouse is G302 ,I set a mouse button when it press down mouse macro implement OutPutLCDMessage()  ， and I create a Winform Control then override the OnDataUpdate method .But run the Winform was ineffective ,how do I do next

**Comment by sidewinder94** [comment]
Hi,
I'd need an example of what you did to try and see what you need to do next.
Though I'd recommend trying to create a simple application to get to know how the library works first.

**Comment by sbblg** [comment]
Logitech device has macro , the macro can output LCD message
I want to use Winform show this message , how can I catch those message

**Comment by sidewinder94** [comment]
The SDK and thus this library does not allow to read from the LCD. Only to write on it.

And again, I need to see what you have tried to do to give advice.

It's pretty straightforwards.

Design a WinForms usercontrol the way you'd normally do.

Make the usercontrol inherit from the Logitech_LCD.Applets.BaseApplet class.

Override the ondataupdate method to update the values of your controls.

Make sure your usercontrol is instanciated by your application when started.

I cannot help you more than this without a precise example.

If you don't care about having a complex UI, you can use the SetBackground, SetTitle and SetText methods in the LogitechLcd class.

**Comment by sidewinder94** [comment]
Well....

As I said in my previous message, the SDK doesn't allow to read from the screen. Thus you won't be able to use my library to read from the screen.

I'd recommend to ask on the logitech forums for help with their macro engine.
